### PR TITLE
add object bitflied stuff

### PR DESCRIPTION
**Pull request by n67094**
Hi, don't hesitate to leave comments for anything so I know for the next time ^^, I hope it's on the good file (it's generics stuff but it seems that it should be here)

### CODE REVIEW

**Comment by LunarLambda** [comment]
Looks good to me. Merging Affine and Hide/Double-Size bits into a "mode" bitfield is interesting.

However the naming I'm not huge on. I thought I had pushed this already, but it might've gotten lost, the naming conventions I had in mind were this:

https://discord.com/channels/768759024270704641/890931966432641054/940511511036719136

Or alternatively, maybe prefixes like `OBJ0`, `OBJ1`, `OBJ2`.

I might not merge this as-is, however it's a good point for discussion on how the object attributes should be named.

**Comment by n67094** [comment]
Ok I agree name are long and boring to write,  reduce them to  `OBJ` seems better than `OBJX`. I mean `OBJX` seems like they are multiple objects, at least to me. tell me and I'll update the code ^^

**Comment by LunarLambda** [comment]
We'll go with just OBJ then. I can put the names in myself and get back to you, hopefully later today. Don't worry about writing a bunch of stuff.

**Comment by LunarLambda** [comment]
Implemented in https://github.com/LunarLambda/libseven/commit/9804339da9806831ef2302d0ef224d08497f0728

Does the naming seem sane? I went with your idea of combining affine+hidden/dsize flags into a 'mode' bitfield, and included aliases for the size bitfield.

**Comment by n67094** [comment]
Hi, seems good to me ^^

Just a NIT things which disturbes me, the x and X between the size (i.ex: 8X8 vs 8x8) 
- in that file it's a lower case 'x'
https://github.com/LunarLambda/libseven/blob/9804339da9806831ef2302d0ef224d08497f0728/include/seven/hw/video.h#L129
- in the object.h file it's an upper case 'X'

The upper case make more sens for a #define

**Comment by LunarLambda** [comment]
yeah. will fix that as well, will be in v0.4.0.  if everything else's okay I would close this?

**Comment by n67094** [comment]
yes perfect, thank you :)

**Pull request closed without merging**
